export const Product_Type = {
  "1": "Brakes",
  "638": "Piston kits & Components",
  "518": "Air Filters",
  "553": "Body",
  "5": "Otros",
};

export const Most_Used_Types = [
  "Piston kits & Components",
  "Engine",
  "Brakes",
  "Clutch",
  "Air Filters",
  "Oil Filters",
  "Drive",
  "Helmets",
  "Exhaust",
  "Sprockets",
  "Tires",
  "Body",
];

export const Product_Type_Translations = {
  Accessories: "Accesorios",
  "Air Filters": "Filtros de Aire",
  "Audio/Visual/Communication": "Audio/Visual/Comunicación",
  Batteries: "Baterías",
  Belts: "Correas",
  "Bicycle Frames": "Cuadros de Bicicleta",
  Bike: "Bicicleta",
  Body: "Carrocería",
  Brakes: "Frenos",
  "Cable/Hydraulic Control Lines": "Líneas de Control Hidráulico/Cable",
  Chains: "Cadenas",
  Chemicals: "Químicos",
  Clamps: "Abrazaderas",
  Clutch: "Embrague",
  Cranks: "Manivelas",
  Drive: "Transmisión",
  Electrical: "Eléctrico",
  Engine: "Motor",
  "Engine Management": "Gestión del Motor",
  Exhaust: "Escape",
  Eyewear: "Gafas",
  "Farm/Agriculture": "Agricultura",
  "Flotation Vests": "Chalecos Salvavidas",
  "Food & Beverage": "Alimentos y Bebidas",
  "Foot Controls": "Controles de Pie",
  Footwear: "Botas",
  Forks: "Horquillas",
  "Fuel Containers": "Contenedores de Combustible",
  "Fuel Tank": "Tanque de Combustible",
  "Gas Caps": "Tapas de Gasolina",
  "Gaskets/Seals": "Juntas/Sellos",
  "Gauges/Meters": "Medidores",
  Gloves: "Guantes",
  GPS: "GPS",
  "Graphics/Decals": "Gráficos/Calcomanías",
  Grips: "Puños",
  "Guards/Braces": "Protectores/Soportes",
  "Hand Controls": "Controles de Mano",
  Handguards: "Protectores de Mano",
  Handlebars: "Manillares",
  "Hardware/Fasteners/Fittings": "Herrajes/Sujetadores/Accesorios",
  Headgear: "Cascos",
  "Helmet Accessories": "Accesorios para Cascos",
  Helmets: "Cascos",
  Hoodies: "Sudaderas",
  Hyfax: "Patines de Cadena",
  "Ice Scratchers": "Rascadores de Hielo",
  Illumination: "Iluminación",
  "Intake/Carb/Fuel System": "Sistema de Admisión/Carburador/Combustible",
  Jackets: "Chaquetas",
  Jerseys: "Camisetas",
  Jets: "Jets",
  Layers: "Capas",
  Levers: "Palancas",
  Luggage: "Equipaje",
  "Mats/Rugs": "Alfombras/Tapetes",
  Mirrors: "Espejos",
  "Mounts/Brackets": "Montajes/Soportes",
  "Oil Filters": "Filtros de Aceite",
  Onesies: "Monos",
  Pants: "Pantalones",
  "Piston kits & Components": "Kits de Pistón y Componentes",
  Plow: "Arado",
  Promotional: "Promocional",
  "Protective/Safety": "Protección/Seguridad",
  Racks: "Portaequipajes",
  "Replacement Parts": "Piezas de Repuesto",
  Rims: "Llantas",
  Risers: "Elevadores",
  Seat: "Asiento",
  Security: "Seguridad",
  Shirts: "Camisas",
  Shoes: "Calzado",
  Shorts: "Pantalones Cortos",
  "Skis/Carbides/Runners": "Esquís/Carburo/Correderas",
  Socks: "Calcetines",
  "Spark Plugs": "Bujías",
  Sprockets: "Coronas / Piñones",
  "Stands/Lifts": "Soportes/Elevadores",
  Starters: "Arranques",
  Steering: "Dirección",
  "Storage Covers": "Fundas de Almacenamiento",
  "Straps/Tie-Downs": "Correas/Amarres",
  Suits: "Trajes",
  Suspension: "Suspensión",
  Sweaters: "Suéteres",
  Switches: "Interruptores",
  "Tank Tops": "Camisetas sin Mangas",
  Throttle: "Acelerador",
  "Tire And Wheel Kit": "Kit de Ruedas y Neumáticos",
  "Tire/Wheel Accessories": "Accesorios de Ruedas/Neumáticos",
  Tires: "Neumáticos",
  Tools: "Herramientas",
  "Track Kit": "Track Kit",
  Tracks: "Tracks",
  "Trailer/Towing": "Remolque/Arrastre",
  "Windshield/Windscreen": "Parabrisas",
  Tubes: "Tubos",
  Undergarments: "Ropa Interior",
  "Utility Containers": "Contenedores Utilitarios",
  "UTV Cab/Roof/Door": "Cabina/Techo/Puerta UTV",
  Vests: "Chalecos",
  Videos: "Videos",
  "Watercraft Towables": "Remolques para Motos de Agua",
  "Wheel Components": "Componentes de Ruedas",
  Wheels: "Ruedas",
  Winch: "Cabrestante",
};

export const brands = [
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/48/2048.jpg?1501504351",
    brandId: "686",
    name: "Brand 1",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/05/228705.jpg?1501504346&updated=202501281226",
    brandId: "99",
    name: "Brand 5",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/80/256180.jpg?1699932899",
    brandId: "454",
    name: "Brand 6",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/60/234660.png?1592284135",
    brandId: "46",
    name: "Brand 8",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/82/582.jpg?1634613701",
    brandId: "137",
    name: "Brand 11",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/43/2143.jpg?1610690995",
    brandId: "206",
    name: "Brand 12",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/90/233690.jpg?1515364052",
    brandId: "223",
    name: "Brand 13",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/60/231960.jpg?1511237916",
    brandId: "220",
    name: "Brand 14",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/50/1750.jpg?1501504351",
    brandId: "348",
    name: "Brand 15",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/50/2050.jpg?1501504351",
    brandId: "662",
    name: "Brand 19",
  },
];

export const featuredBrands = [
  { name: "ACERBIS", id: "692" },
  { name: "ALPINESTARS", id: "769" },
  { name: "FLY RACING", id: "135" },
  { name: "FMF", id: "137" },
  { name: "VERTEX", id: "662" },
  { name: "PROX", id: "454" },
  { name: "WISECO", id: "686" },
  { name: "RACETECH", id: "467" },
  { name: "CYLINDER WORKS", id: "46" },
  { name: "HOT CAMS", id: "220" },
  { name: "HOT RODS", id: "223" },
  { name: "MOTO TASSINARI", id: "348" },
  { name: "HINSON", id: "206" },
  { name: "GAERNE", id: "159" },
  { name: "ALL BALLS", id: "99" },
  { name: "PIVOT WORKS", id: "419" },
];

export const casualTranslations = {
  Headgear: "Gorros",
  Shirts: "Remeras",
  Hoodies: "Buzos",
  Jackets: "Chaquetas",
  Pants: "Pantalones",
  Shoes: "Zapatos",
  Shorts: "Shorts",
  Sweaters: "Suéteres",
  Vests: "Chalecos",
};

export const apparelTranslations = {
  "Protective/Safety": "Protección y Seguridad",
  Eyewear: "Gafas / Lentes",
  Footwear: "Calzado",
  Gloves: "Guantes",
  Jackets: "Camperas",
  Jerseys: "Jerseys",
  Pants: "Pantalones",
  Helmets: "Cascos",
  Socks: "Medias",
  Suits: "Trajes",
};

export const ProductTypeUrlMap = {
  "Protective/Safety": "protective-safety",
  "Tank Tops": "tank-tops",
  "protective-safety": "Protective/Safety",
  "Air Filters": "air-filters",
  "Hardware/Fasteners/Fittings": "hardware-fasteners-fittings",
  "Piston kits & Components": "piston-kits-components",
  "Mounts/Brackets": "mounts-brackets",
  "Replacement Parts": "replacement-parts",
  "UTV Cab/Roof/Door": "utv-cab-roof-door",
  "Foot Controls": "foot-controls",
  "Utility Containers": "utility-containers",
  "Track Kit": "track-kit",
  "Cable/Hydraulic Control Lines": "cable-hydraulic-control-lines",
  "Gauges/Meters": "gauges-meters",
  "Intake/Carb/Fuel System": "intake-carb-fuel-system",
  "Engine Management": "engine-management",
  "Fuel Tank": "fuel-tanks",
  "Gas Caps": "gas-caps",
  "Graphics/Decals": "graphics-decals",
  "Guards/Braces": "guards-braces",
  "Hand Controls": "hand-controls",
  "Spark Plugs": "spark-plugs",
  "Oil Filters": "oil-filters",
};

export const ProductTypeUrlReverseMap = {
  "protective-safety": "Protective/Safety",
  "tank-tops": "Tank Tops",
  "piston-kits-components": "Piston kits & Components",
  "mounts-brackets": "Mounts/Brackets",
  "replacement-parts": "Replacement Parts",
  "utv-cab-roof-door": "UTV Cab/Roof/Door",
  "foot-controls": "Foot Controls",
  "utility-containers": "Utility Containers",
  "track-kit": "Track Kit",
  "air-filters": "Air Filters",
  "hardware-fasteners-fittings": "Hardware/Fasteners/Fittings",
  "cable-hydraulic-control-lines": "Cable/Hydraulic Control Lines",
  "gauges-meters": "Gauges/Meters",
  "intake-carb-fuel-system": "Intake/Carb/Fuel System",
  "engine-management": "Engine Management",
  "fuel-tanks": "Fuel Tank",
  "gas-caps": "Gas Caps",
  "graphics-decals": "Graphics/Decals",
  "guards-braces": "Guards/Braces",
  "hand-controls": "Hand Controls",
  "spark-plugs": "Spark Plugs",
  "oil-filters": "Oil Filters",
};

export const TiresBrands = [
  { name: "BFGoodrich", id: "841" },
  { name: "Dunlop", id: "1085" },
  { name: "Gbc", id: "169" },
  { name: "IRC", id: "237" },
  { name: "ITP", id: "239" },
  { name: "Maxxis", id: "322" },
  { name: "Metzeler", id: "329" },
  { name: "Michelin", id: "330" },
  { name: "Pirelli", id: "417" },
  { name: "Sedona", id: "522" },
  { name: "Shinko", id: "529" },
  { name: "System 3", id: "3262" },
];

export const productTypeMap: Record<string, string> = {
  'motor': 'Engine,Piston kits & Components',
  'accesorios': 'Accessories,Drive',
  'indumentaria': 'Pants,Jerseys,Footwear,Gloves,Eyewear',
  'cascos': 'Helmets,Protective/Safety',
  'proteccion': 'Protective/Safety,Luggage,Bags',
  'herramientas': 'Tools',
  'casual': 'Vests,Sweaters,Suits,Socks,Shorts,Shoes,Jackets,Hoodies,Bags,Luggage',
  'protective-safety': 'Protective/Safety',
  'air-filters': 'Air Filters',  
  'tank-tops': 'Tank Tops',
  'piston-kits-components': 'Piston kits & Components',
  'mounts-brackets': 'Mounts/Brackets',
  'replacement-parts': 'Replacement Parts',
  'utv-cab-roof-door': 'UTV Cab/Roof/Door',
  'foot-controls': 'Foot Controls',
  'utility-containers': 'Utility Containers',
  'track-kit': 'Track Kit',
  'hardware-fasteners-fittings': 'Hardware/Fasteners/Fittings',
  'cable-hydraulic-control-lines': 'Cable/Hydraulic Control Lines',
  'gauges-meters': 'Gauges/Meters',
  'intake-carb-fuel-system': 'Intake/Carb/Fuel System',
  'engine-management': 'Engine Management',
  'fuel-tanks': 'Fuel Tank',
  'gas-caps': 'Gas Caps',
  'graphics-decals': 'Graphics/Decals',
  'guards-braces': 'Guards/Braces',
  'hand-controls': 'Hand Controls',
  'spark-plugs': 'Spark Plugs',
  'oil-filters': 'Oil Filters',
};
