export const Product_Type = {
    '1': 'Brakes',
    '638': 'Piston kits & Components',
    '518': 'Air Filters',
    '553': 'Body',
    '5': 'Otros',
}

export const Most_Used_Types = [
    'Piston kits & Components',
    'Engine',
    'Brakes',
    'Clutch',
    'Air Filters',
    'Oil Filters',
    'Drive',
    'Helmets',
    'Exhaust',
    'Sprockets',
    'Tires',
    'Body'
];

export const Product_Type_Translations = {
    'Accessories': 'Accesorios',
    'Air Filters': 'Filtros de Aire',
    'Audio/Visual/Communication': 'Audio/Visual/Comunicación',
    'Batteries': 'Baterías',
    'Belts': 'Correas',
    'Bicycle Frames': 'Cuadros de Bicicleta',
    'Bike': 'Bicicleta',
    'Body': 'Carrocería',
    'Brakes': 'Frenos',
    'Cable/Hydraulic Control Lines': 'Líneas de Control Hidráulico/Cable',
    'Chains': 'Cadenas',
    'Chemicals': 'Químicos',
    'Clamps': 'Abrazaderas',
    'Clutch': 'Embrague',
    'Cranks': 'Manivelas',
    'Drive': 'Transmisión',
    'Electrical': 'Eléctrico',
    'Engine': 'Motor',
    'Engine Management': 'Gestión del Motor',
    'Exhaust': 'Escape',
    'Eyewear': 'Gafas',
    'Farm/Agriculture': 'Agricultura',
    'Flotation Vests': 'Chalecos Salvavidas',
    'Food & Beverage': 'Alimentos y Bebidas',
    'Foot Controls': 'Controles de Pie',
    'Footwear': 'Botas',
    'Forks': 'Horquillas',
    'Fuel Containers': 'Contenedores de Combustible',
    'Fuel Tank': 'Tanque de Combustible',
    'Gas Caps': 'Tapas de Gasolina',
    'Gaskets/Seals': 'Juntas/Sellos',
    'Gauges/Meters': 'Medidores',
    'Gloves': 'Guantes',
    'GPS': 'GPS',
    'Graphics/Decals': 'Gráficos/Calcomanías',
    'Grips': 'Puños',
    'Guards/Braces': 'Protectores/Soportes',
    'Hand Controls': 'Controles de Mano',
    'Handguards': 'Protectores de Mano',
    'Handlebars': 'Manillares',
    'Hardware/Fasteners/Fittings': 'Herrajes/Sujetadores/Accesorios',
    'Headgear': 'Cascos',
    'Helmet Accessories': 'Accesorios para Cascos',
    'Helmets': 'Cascos',
    'Hoodies': 'Sudaderas',
    'Hyfax': 'Patines de Cadena',
    'Ice Scratchers': 'Rascadores de Hielo',
    'Illumination': 'Iluminación',
    'Intake/Carb/Fuel System': 'Sistema de Admisión/Carburador/Combustible',
    'Jackets': 'Chaquetas',
    'Jerseys': 'Camisetas',
    'Jets': 'Jets',
    'Layers': 'Capas',
    'Levers': 'Palancas',
    'Luggage': 'Equipaje',
    'Mats/Rugs': 'Alfombras/Tapetes',
    'Mirrors': 'Espejos',
    'Mounts/Brackets': 'Montajes/Soportes',
    'Oil Filters': 'Filtros de Aceite',
    'Onesies': 'Monos',
    'Pants': 'Pantalones',
    'Piston kits & Components': 'Kits de Pistón y Componentes',
    'Plow': 'Arado',
    'Promotional': 'Promocional',
    'Protective/Safety': 'Protección/Seguridad',
    'Racks': 'Portaequipajes',
    'Replacement Parts': 'Piezas de Repuesto',
    'Rims': 'Llantas',
    'Risers': 'Elevadores',
    'Seat': 'Asiento',
    'Security': 'Seguridad',
    'Shirts': 'Camisas',
    'Shoes': 'Calzado',
    'Shorts': 'Pantalones Cortos',
    'Skis/Carbides/Runners': 'Esquís/Carburo/Correderas',
    'Socks': 'Calcetines',
    'Spark Plugs': 'Bujías',
    'Sprockets': 'Coronas / Piñones',
    'Stands/Lifts': 'Soportes/Elevadores',
    'Starters': 'Arranques',
    'Steering': 'Dirección',
    'Storage Covers': 'Fundas de Almacenamiento',
    'Straps/Tie-Downs': 'Correas/Amarres',
    'Suits': 'Trajes',
    'Suspension': 'Suspensión',
    'Sweaters': 'Suéteres',
    'Switches': 'Interruptores',
    'Tank Tops': 'Camisetas sin Mangas',
    'Throttle': 'Acelerador',
    'Tire And Wheel Kit': 'Kit de Ruedas y Neumáticos',
    'Tire/Wheel Accessories': 'Accesorios de Ruedas/Neumáticos',
    'Tires': 'Neumáticos',
    'Tools': 'Herramientas',
    'Track Kit': 'Track Kit',
    'Tracks': 'Tracks',
    'Trailer/Towing': 'Remolque/Arrastre',
    'Windshield/Windscreen': 'Parabrisas',
    'Tubes': 'Tubos',
    'Undergarments': 'Ropa Interior',
    'Utility Containers': 'Contenedores Utilitarios',
    'UTV Cab/Roof/Door': 'Cabina/Techo/Puerta UTV',
    'Vests': 'Chalecos',
    'Videos': 'Videos',
    'Watercraft Towables': 'Remolques para Motos de Agua',
    'Wheel Components': 'Componentes de Ruedas',
    'Wheels': 'Ruedas',
    'Winch': 'Cabrestante'
}

export const brands = [
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/48/2048.jpg?1501504351",
      brandId: "686",
      name: "Brand 1",
    },

    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/01/234701.jpg?1566435970",
      brandId: "419",
      name: "Brand 5",
    },
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/80/256180.jpg?1699932899",
      brandId: "454",
      name: "Brand 6",
    },

    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/60/234660.png?1592284135",
      brandId: "46",
      name: "Brand 8",
    },

    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/82/582.jpg?1634613701",
      brandId: "137",
      name: "Brand 11",
    },
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/43/2143.jpg?1610690995",
      brandId: "206",
      name: "Brand 12",
    },
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/90/233690.jpg?1515364052",
      brandId: "223",
      name: "Brand 13",
    },
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/60/231960.jpg?1511237916",
      brandId: "220",
      name: "Brand 14",
    },
    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/50/1750.jpg?1501504351",
      brandId: "348",
      name: "Brand 15",
    },

    {
      imgUrl:
        "https://www.mxstore.com.au/assets/webshop/cms/50/2050.jpg?1501504351",
      brandId: "662",
      name: "Brand 19",
    },
  ];