export const Product_Type = {
  "1": "Brakes",
  "638": "Piston kits & Components",
  "518": "Air Filters",
  "553": "Body",
  "5": "Otros",
};

export const Most_Used_Types = [
  "Accessories",
  "Air Filters",
  "Brakes",
  "Engine",
  "Exhaust",
  "Helmets",
  "Lighting",
  "Oil Filters",
  "Suspension",
  "Tools"
];

export const Product_Type_Translations: { [key: string]: string } = {
  "Accessories": "Accesorios",
  "Air Filters": "Filtros de Aire",
  "Apparel": "Indumentaria",
  "Bags": "Bolsos",
  "Batteries": "Baterías",
  "Belts": "Correas",
  "Body": "Plasticos / Accesorios",
  "Brakes": "Frenos",
  "Cable/Hydraulic Control Lines": "Líneas de Control Hidráulico/Cable",
  "Chains": "Cadenas",
  "Chemicals": "Aceites",
  "Clutch": "Embrague",
  "Cooling System": "Sistema de Refrigeración",
  "Drive": "Transmisión",
  "Electrical": "Eléctrico",
  "Engine": "Motor",
  "Engine Management": "Gestión del Motor",
  "Exhaust": "Escape",
  "Eyewear": "Antiparras",
  "Foot Controls": "Controles de Pie",
  "Footwear": "Calzado",
  "Fuel Tank": "Tanque de Combustible",
  "Gas Caps": "Tapas de Combustible",
  "Gaskets/Seals": "Kit de Juntas y Retenes",
  "Gauges/Meters": "Medidores/Indicadores",
  "Gloves": "Guantes",
  "Graphics/Decals": "Gráficos/Calcomanías",
  "Grips": "Puños",
  "Guards/Braces": "Protectores/Soportes",
  "Hand Controls": "Controles Manuales",
  "Handguards": "Protectores de Manos",
  "Handlebars": "Manubrios",
  "Hardware/Fasteners/Fittings": "Herrajes/Sujetadores/Accesorios",
  "Helmets": "Cascos",
  "Hoodies": "Buzos",
  "Intake/Carb/Fuel System": "Sistema de Admisión/Carburador/Combustible",
  "Jackets": "Camperas",
  "Jerseys": "Jerseys",
  "Jets": "Jets de Carburador",
  "Levers": "Palancas",
  "Lighting": "Iluminación",
  "Luggage": "Equipaje",
  "Maintenance": "Mantenimiento",
  "Mirrors": "Espejos",
  "Oil Filters": "Filtros de Aceite",
  "Oils": "Aceites",
  "Pants": "Pantalones",
  "Piston kits & Components": "Kits de Pistón y Componentes",
  "Protective/Safety": "Protección/Seguridad",
  "Replacement Parts": "Repuestos de Accesorios",
  "Seat": "Asiento",
  "Shirts": "Remeras",
  "Shorts": "Shorts",
  "Socks": "Medias",
  "Spark Plugs": "Bujías",
  "Sprockets": "Coronas y Piñones",
  "Starters": "Arranques",
  "Steering": "Dirección",
  "Suspension": "Suspensión",
  "Sweaters": "Suéteres",
  "Tank Tops": "Musculosas",
  "Throttle": "Acelerador",
  "Tools": "Herramientas",
  "Track Kit": "Kit de Pista",
  "Utility Containers": "Contenedores Utilitarios",
  "Vests": "Chalecos",
  "Wheels": "Ruedas"
};

export const brands = [
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/48/2048.jpg?1501504351",
    brandId: "686",
    name: "WISECO",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/05/228705.jpg?1501504346&updated=202501281226",
    brandId: "99",
    name: "ALL BALLS",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/80/256180.jpg?1699932899",
    brandId: "454",
    name: "PROX",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/60/234660.png?1592284135",
    brandId: "46",
    name: "CYLINDER WORKS",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/82/582.jpg?1634613701",
    brandId: "137",
    name: "FMF",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/43/2143.jpg?1610690995",
    brandId: "206",
    name: "HINSON",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/90/233690.jpg?1515364052",
    brandId: "223",
    name: "HOT RODS",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/60/231960.jpg?1511237916",
    brandId: "220",
    name: "HOT CAMS",
  },
  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/50/1750.jpg?1501504351",
    brandId: "348",
    name: "MOTO TASSINARI",
  },

  {
    imgUrl:
      "https://www.mxstore.com.au/assets/webshop/cms/50/2050.jpg?1501504351",
    brandId: "662",
    name: "VERTEX",
  },
];

export const featuredBrands = [
  { name: "ACERBIS", id: "692" },
  { name: "ALPINESTARS", id: "769" },
  { name: "FLY RACING", id: "135" },
  { name: "FMF", id: "137" },
  { name: "VERTEX", id: "662" },
  { name: "PROX", id: "454" },
  { name: "WISECO", id: "686" },
  { name: "RACETECH", id: "467" },
  { name: "CYLINDER WORKS", id: "46" },
  { name: "HOT CAMS", id: "220" },
  { name: "HOT RODS", id: "223" },
  { name: "MOTO TASSINARI", id: "348" },
  { name: "HINSON", id: "206" },
  { name: "GAERNE", id: "159" },
  { name: "ALL BALLS", id: "99" },
  { name: "PIVOT WORKS", id: "419" },
];

export const casualTranslations = {
  Headgear: "Gorros",
  Shirts: "Remeras",
  Hoodies: "Buzos",
  Jackets: "Chaquetas",
  Pants: "Pantalones",
  Shoes: "Zapatos",
  Shorts: "Shorts",
  Sweaters: "Suéteres",
  Vests: "Chalecos",
};

export const apparelTranslations = {
  "Protective/Safety": "Protección y Seguridad",
  Eyewear: "Antiparras",
  Footwear: "Botas",
  Gloves: "Guantes",
  Jackets: "Camperas",
  Jerseys: "Jerseys",
  Pants: "Pantalones",
  Helmets: "Cascos",
  Socks: "Medias",
  Suits: "Trajes",
};

export const ProductTypeUrlMap = {
  // Casual
  Headgear: "gorros",
  Shirts: "remeras",
  Hoodies: "buzos",
  Shoes: "zapatos",
  Shorts: "shorts",
  Sweaters: "sueteres",
  Vests: "chalecos",
  
  // Indumentaria
  "Protective/Safety": "proteccion-y-seguridad",
  Eyewear: "antiparras",
  Footwear: "botas",
  Gloves: "guantes",
  Jackets: "camperas",
  Jerseys: "jerseys",
  Pants: "pantalones",
  Helmets: "cascos",
  Socks: "medias",
  Suits: "trajes",
  
  // Repuestos
  Brakes: "frenos",
  Engine: "motor",
  "Piston kits & Components": "kit-de-pistones",
  Chemicals: "aceites",
  Body: "plasticos",
  Clutch: "embrague",
  Exhaust: "escape",
  "Air Filters": "filtros-de-aire",
  "Gaskets/Seals": "kit-de-juntas",
  Batteries: "baterias",
  Belts: "correas",
  "Cable/Hydraulic Control Lines": "cables",
  Chains: "cadena",
  Drive: "transmision",
  Electrical: "electronica",
  "Engine Management": "cdi-ecu",
  "Foot Controls": "pedales",
  Forks: "suspension",
  "Fuel Tank": "tanques-de-nafta",
  "Gas Caps": "tapas-de-tanque",
  "Gauges/Meters": "velocimetros",
  "Intake/Carb/Fuel System": "carburadores-inyeccion",
  "Graphics/Decals": "graficos",
  Grips: "punos",
  Handguards: "cubre-manos",
  Handlebars: "manubrios",
  "Hardware/Fasteners/Fittings": "tornilleria",
  Illumination: "luces",
  Jets: "reparacion-carburadores",
  Levers: "palancas",
  Mirrors: "espejos",
  "Oil Filters": "filtros-de-aceite",
  Seat: "asientos",
  "Spark Plugs": "bujias-y-capuchones",
  Sprockets: "coronas-y-pinones",
  Starters: "arranques",
  Steering: "direccion",
  Throttle: "acelerador",
  Tools: "herramientas",
  "Guards/Braces": "protecciones",
  "Hand Controls": "controles-manubrios",
  
  // Existing technical mappings
  "Mounts/Brackets": "mounts-brackets",
  "Replacement Parts": "replacement-parts",
  "UTV Cab/Roof/Door": "utv-cab-roof-door",
  "Utility Containers": "utility-containers",
  "Track Kit": "track-kit"
};

export const ProductTypeUrlReverseMap = {
  // Casual
  "gorros": "Headgear",
  "remeras": "Shirts",
  "buzos": "Hoodies",
  "zapatos": "Shoes",
  "shorts": "Shorts",
  "sueteres": "Sweaters",
  "chalecos": "Vests",
  
  // Indumentaria
  "proteccion-y-seguridad": "Protective/Safety",
  "antiparras": "Eyewear",
  "botas": "Footwear",
  "guantes": "Gloves",
  "camperas": "Jackets",
  "jerseys": "Jerseys",
  "pantalones": "Pants",
  "cascos": "Helmets",
  "medias": "Socks",
  "trajes": "Suits",
  
  // Repuestos
  "frenos": "Brakes",
  "motor": "Engine",
  "kit-de-pistones": "Piston kits & Components",
  "aceites": "Chemicals",
  "plasticos": "Body",
  "embrague": "Clutch",
  "escape": "Exhaust",
  "filtros-de-aire": "Air Filters",
  "kit-de-juntas": "Gaskets/Seals",
  "baterias": "Batteries",
  "correas": "Belts",
  "cables": "Cable/Hydraulic Control Lines",
  "cadena": "Chains",
  "transmision": "Drive",
  "electronica": "Electrical",
  "cdi-ecu": "Engine Management",
  "pedales": "Foot Controls",
  "suspension": "Forks",
  "tanques-de-nafta": "Fuel Tank",
  "tapas-de-tanque": "Gas Caps",
  "velocimetros": "Gauges/Meters",
  "carburadores-inyeccion": "Intake/Carb/Fuel System",
  "graficos": "Graphics/Decals",
  "punos": "Grips",
  "cubre-manos": "Handguards",
  "manubrios": "Handlebars",
  "tornilleria": "Hardware/Fasteners/Fittings",
  "luces": "Illumination",
  "reparacion-carburadores": "Jets",
  "palancas": "Levers",
  "espejos": "Mirrors",
  "filtros-de-aceite": "Oil Filters",
  "asientos": "Seat",
  "bujias-y-capuchones": "Spark Plugs",
  "coronas-y-pinones": "Sprockets",
  "arranques": "Starters",
  "direccion": "Steering",
  "acelerador": "Throttle",
  "herramientas": "Tools",
  "protecciones": "Guards/Braces",
  "controles-manubrios": "Hand Controls",
  
  // Existing technical mappings
  "mounts-brackets": "Mounts/Brackets",
  "replacement-parts": "Replacement Parts",
  "utv-cab-roof-door": "UTV Cab/Roof/Door",
  "utility-containers": "Utility Containers",
  "track-kit": "Track Kit"
};

export const TiresBrands = [
  { name: "BFGoodrich", id: "841" },
  { name: "Dunlop", id: "1085" },
  { name: "Gbc", id: "169" },
  { name: "IRC", id: "237" },
  { name: "ITP", id: "239" },
  { name: "Maxxis", id: "322" },
  { name: "Metzeler", id: "329" },
  { name: "Michelin", id: "330" },
  { name: "Pirelli", id: "417" },
  { name: "Sedona", id: "522" },
  { name: "Shinko", id: "529" },
  { name: "System 3", id: "3262" },
];

export const productTypeMap: Record<string, string> = {
  'motor': 'Engine,Piston kits & Components',
  'accesorios': 'Accessories,Drive',
  'indumentaria': 'Pants,Jerseys,Footwear,Gloves,Eyewear',
  'cascos': 'Helmets,Protective/Safety',
  'proteccion': 'Protective/Safety,Luggage,Bags',
  'herramientas': 'Tools',
  'casual': 'Vests,Sweaters,Suits,Socks,Shorts,Shoes,Jackets,Hoodies,Bags,Luggage',
  'protective-safety': 'Protective/Safety',
  'air-filters': 'Air Filters',  
  'tank-tops': 'Tank Tops',
  'piston-kits-components': 'Piston kits & Components',
  'mounts-brackets': 'Mounts/Brackets',
  'replacement-parts': 'Replacement Parts',
  'utv-cab-roof-door': 'UTV Cab/Roof/Door',
  'foot-controls': 'Foot Controls',
  'utility-containers': 'Utility Containers',
  'track-kit': 'Track Kit',
  'hardware-fasteners-fittings': 'Hardware/Fasteners/Fittings',
  'cable-hydraulic-control-lines': 'Cable/Hydraulic Control Lines',
  'gauges-meters': 'Gauges/Meters',
  'intake-carb-fuel-system': 'Intake/Carb/Fuel System',
  'engine-management': 'Engine Management',
  'fuel-tanks': 'Fuel Tank',
  'gas-caps': 'Gas Caps',
  'graphics-decals': 'Graphics/Decals',
  'guards-braces': 'Guards/Braces',
  'hand-controls': 'Hand Controls',
  'spark-plugs': 'Spark Plugs',
  'oil-filters': 'Oil Filters',
};

